filter:
  excluded_paths:
    - +/
    - assets/
    - languages/
    - node_modules/
    - vendor/

build:
  nodes:
    analysis:
      cache:
        disabled: false
        directories:
          - ~/.composer/cache
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress
      environment:
        node: false
        php: '7.3'
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
  php_code_sniffer:
    config:
      standard: WordPress
  sensiolabs_security_checker: true

checks:
  php:
    no_exit: false
    simplify_boolean_return: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
