bump:
  - readme.txt
  - blackbar.php
language:
  destination: languages/
  domain: blackbar
  team: Gemini Labs <support@geminilabs.io>
  translator: Paul Ryley <paul@geminilabs.io>
  watch:
    - plugin/**/*.php
    - views/**/*.php
    - '*.php'
